import puppeteer from 'puppeteer';
const browser = await puppeteer.launch({ args: ['--no-sandbox', '--disable-setuid-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
await page.goto('http://localhost:4321/', { waitUntil: 'networkidle2', timeout: 30000 });
await new Promise(r => setTimeout(r, 1000));
await page.evaluate(() => document.getElementById('publications')?.scrollIntoView());
await new Promise(r => setTimeout(r, 600));
await page.screenshot({ path: 'temporary screenshots/check-main-pubs.png' });
await browser.close();
console.log('done');
